providers = ["python"]

[install]
cmd = "pip install poetry && poetry install"
  
[start]
cmd = "pip install poetry && poetry lock --no-update && poetry install && poetry shell && python run.py"
